# Generated by Django 4.2.5 on 2025-01-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
