# Generated by Django 4.2.5 on 2025-02-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atypical_pronunciation.difficulty')),
            ],
        ),
    ]
