# Generated by Django 4.2.5 on 2025-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0003_difficulty_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='module',
            name='diff',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
