# Generated by Django 4.2.5 on 2025-02-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0004_remove_module_difficulty_module_diff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=255)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atypical_pronunciation.module')),
            ],
        ),
    ]
