# Generated by Django 4.2.5 on 2025-02-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0005_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='audio',
            field=models.FileField(default='settings.MEDIA_ROOT/mp3/1449423-1241067.mp3', upload_to='mp3/'),
        ),
    ]
