# Generated by Django 4.2.5 on 2025-02-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0006_phrase_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_phrases', models.ManyToManyField(related_name='completed_by', to='atypical_pronunciation.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
