# Generated by Django 4.2.5 on 2025-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0007_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='module_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_phrases',
            field=models.ManyToManyField(to='atypical_pronunciation.phrase'),
        ),
    ]
