# Generated by Django 4.2.5 on 2025-02-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0008_progress_module_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='module_score',
        ),
    ]
