# Generated by Django 4.2.5 on 2025-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0009_remove_progress_module_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='module_score',
            field=models.IntegerField(default=0),
        ),
    ]
