# Generated by Django 4.2.5 on 2025-02-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0010_progress_module_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='score_easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='score_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='score_medium',
            field=models.IntegerField(default=0),
        ),
    ]
