# Generated by Django 4.2.5 on 2025-02-05 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0011_progress_score_easy_progress_score_hard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='module_score',
        ),
    ]
