# Generated by Django 4.2.5 on 2025-02-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0014_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='decoded/'),
        ),
    ]
