# Generated by Django 4.2.5 on 2025-02-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atypical_pronunciation', '0015_answer_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='atypical_pronunciation.phrase'),
        ),
    ]
